#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x6c9dadc8, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xd4110e55, __VMLINUX_SYMBOL_STR(register_netdevice) },
	{ 0x569504a5, __VMLINUX_SYMBOL_STR(kobject_put) },
	{ 0x31e791fd, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xebdbb10e, __VMLINUX_SYMBOL_STR(neigh_lookup) },
	{ 0xee57ea5d, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xc5b471a1, __VMLINUX_SYMBOL_STR(stp_proto_unregister) },
	{ 0x514a0b5a, __VMLINUX_SYMBOL_STR(sysfs_remove_bin_file) },
	{ 0x5fc56a46, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0x7b52e38, __VMLINUX_SYMBOL_STR(rtnl_unregister) },
	{ 0x91eb9b4, __VMLINUX_SYMBOL_STR(round_jiffies) },
	{ 0xb3cce52b, __VMLINUX_SYMBOL_STR(netdev_notice) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x6c09c2a4, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x278ea2d9, __VMLINUX_SYMBOL_STR(dev_get_flags) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0xad4968f4, __VMLINUX_SYMBOL_STR(dev_disable_lro) },
	{ 0xd3dbfbc4, __VMLINUX_SYMBOL_STR(_find_first_zero_bit_le) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0x29a023cf, __VMLINUX_SYMBOL_STR(dev_uc_add) },
	{ 0x2e947e52, __VMLINUX_SYMBOL_STR(netdev_rx_handler_register) },
	{ 0xc7a4fbed, __VMLINUX_SYMBOL_STR(rtnl_lock) },
	{ 0x1eddc263, __VMLINUX_SYMBOL_STR(arp_tbl) },
	{ 0x3e6f8dbb, __VMLINUX_SYMBOL_STR(kobject_uevent) },
	{ 0x9eb9cf9b, __VMLINUX_SYMBOL_STR(netif_carrier_on) },
	{ 0xa1d55e90, __VMLINUX_SYMBOL_STR(_raw_spin_lock_bh) },
	{ 0x84dcc971, __VMLINUX_SYMBOL_STR(skb_clone) },
	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
	{ 0xd3f57a2, __VMLINUX_SYMBOL_STR(_find_next_bit_le) },
	{ 0x2124474, __VMLINUX_SYMBOL_STR(ip_send_check) },
	{ 0xd2da1048, __VMLINUX_SYMBOL_STR(register_netdevice_notifier) },
	{ 0x8388b264, __VMLINUX_SYMBOL_STR(netif_carrier_off) },
	{ 0x456ee342, __VMLINUX_SYMBOL_STR(rtnl_notify) },
	{ 0x4cb6da37, __VMLINUX_SYMBOL_STR(dev_set_allmulti) },
	{ 0xc52ee121, __VMLINUX_SYMBOL_STR(is_skb_forwardable) },
	{ 0xadc7126d, __VMLINUX_SYMBOL_STR(call_netdevice_notifiers) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x28cc25db, __VMLINUX_SYMBOL_STR(arm_copy_from_user) },
	{ 0x33ec1a28, __VMLINUX_SYMBOL_STR(kobject_del) },
	{ 0x63c966ee, __VMLINUX_SYMBOL_STR(neigh_destroy) },
	{ 0xf499fdb2, __VMLINUX_SYMBOL_STR(rcu_barrier_bh) },
	{ 0x28aa6a67, __VMLINUX_SYMBOL_STR(call_rcu) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xf22a3450, __VMLINUX_SYMBOL_STR(sysfs_remove_group) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xc9ec4e21, __VMLINUX_SYMBOL_STR(free_percpu) },
	{ 0x9d0d6206, __VMLINUX_SYMBOL_STR(unregister_netdevice_notifier) },
	{ 0xf4fa543b, __VMLINUX_SYMBOL_STR(arm_copy_to_user) },
	{ 0x4bdf868d, __VMLINUX_SYMBOL_STR(skb_trim) },
	{ 0x1136bba9, __VMLINUX_SYMBOL_STR(kobject_create_and_add) },
	{ 0x9cb338aa, __VMLINUX_SYMBOL_STR(netdev_master_upper_dev_link) },
	{ 0x5dca63c, __VMLINUX_SYMBOL_STR(__netdev_alloc_skb) },
	{ 0xe9f3a984, __VMLINUX_SYMBOL_STR(ip_mc_check_igmp) },
	{ 0x3d92e94b, __VMLINUX_SYMBOL_STR(netif_rx) },
	{ 0xc65b9b79, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0xf1db1704, __VMLINUX_SYMBOL_STR(nla_memcpy) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x706d051c, __VMLINUX_SYMBOL_STR(del_timer_sync) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xb45f2d4, __VMLINUX_SYMBOL_STR(__cpu_possible_mask) },
	{ 0x5fc14705, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x9fdecc31, __VMLINUX_SYMBOL_STR(unregister_netdevice_many) },
	{ 0xc6eac8af, __VMLINUX_SYMBOL_STR(sysfs_rename_link_ns) },
	{ 0x70a52ccc, __VMLINUX_SYMBOL_STR(stp_proto_register) },
	{ 0x37befc70, __VMLINUX_SYMBOL_STR(jiffies_to_msecs) },
	{ 0xaa2b1121, __VMLINUX_SYMBOL_STR(__ethtool_get_link_ksettings) },
	{ 0x6d294e43, __VMLINUX_SYMBOL_STR(clock_t_to_jiffies) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xb02cd086, __VMLINUX_SYMBOL_STR(ethtool_op_get_link) },
	{ 0x20c55ae0, __VMLINUX_SYMBOL_STR(sscanf) },
	{ 0x3c3fce39, __VMLINUX_SYMBOL_STR(__local_bh_enable_ip) },
	{ 0x77401c0b, __VMLINUX_SYMBOL_STR(sysfs_create_group) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x9b8c3443, __VMLINUX_SYMBOL_STR(inet_select_addr) },
	{ 0x5c54b7e6, __VMLINUX_SYMBOL_STR(ns_capable) },
	{ 0xd6aeee52, __VMLINUX_SYMBOL_STR(__skb_warn_lro_forwarding) },
	{ 0x8fde4f8c, __VMLINUX_SYMBOL_STR(kobject_init_and_add) },
	{ 0xcd279169, __VMLINUX_SYMBOL_STR(nla_find) },
	{ 0x5f2e00fb, __VMLINUX_SYMBOL_STR(free_netdev) },
	{ 0x7027a9f6, __VMLINUX_SYMBOL_STR(llc_mac_hdr_init) },
	{ 0x9caedd59, __VMLINUX_SYMBOL_STR(register_netdev) },
	{ 0x33d70ab8, __VMLINUX_SYMBOL_STR(nla_put) },
	{ 0xe5e340fd, __VMLINUX_SYMBOL_STR(netif_receive_skb) },
	{ 0xad3eadc4, __VMLINUX_SYMBOL_STR(netdev_upper_dev_unlink) },
	{ 0x84b183ae, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0xd1ebe643, __VMLINUX_SYMBOL_STR(ndo_dflt_fdb_dump) },
	{ 0x73e20c1c, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0xa5df38a7, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0xa4c01ba6, __VMLINUX_SYMBOL_STR(skb_push) },
	{ 0x879f16c3, __VMLINUX_SYMBOL_STR(rtnl_register) },
	{ 0xd48f643f, __VMLINUX_SYMBOL_STR(arp_send) },
	{ 0xf4f14de6, __VMLINUX_SYMBOL_STR(rtnl_trylock) },
	{ 0xc5fdef94, __VMLINUX_SYMBOL_STR(call_usermodehelper) },
	{ 0x16e5c2a, __VMLINUX_SYMBOL_STR(mod_timer) },
	{ 0xbc3f1676, __VMLINUX_SYMBOL_STR(rtnl_af_unregister) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0xcd1ce500, __VMLINUX_SYMBOL_STR(sysfs_remove_link) },
	{ 0xa1cf95b0, __VMLINUX_SYMBOL_STR(skb_pull) },
	{ 0x1cd74c47, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0xd54f41ce, __VMLINUX_SYMBOL_STR(try_to_del_timer_sync) },
	{ 0x76be8b3, __VMLINUX_SYMBOL_STR(rtnl_link_unregister) },
	{ 0x5a5cfd9e, __VMLINUX_SYMBOL_STR(__dev_get_by_index) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0x6c209eab, __VMLINUX_SYMBOL_STR(__alloc_percpu_gfp) },
	{ 0xcbdde174, __VMLINUX_SYMBOL_STR(ipv6_dev_get_saddr) },
	{ 0xfd77d40c, __VMLINUX_SYMBOL_STR(sysfs_create_link) },
	{ 0xcba24c82, __VMLINUX_SYMBOL_STR(rtnl_set_sk_err) },
	{ 0x17506ac5, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x38a06b32, __VMLINUX_SYMBOL_STR(__alloc_skb) },
	{ 0xbba9eae, __VMLINUX_SYMBOL_STR(rtnl_af_register) },
	{ 0xdd3916ac, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_bh) },
	{ 0x4f391d0e, __VMLINUX_SYMBOL_STR(nla_parse) },
	{ 0xf4064208, __VMLINUX_SYMBOL_STR(netdev_rx_handler_unregister) },
	{ 0xea6f44f0, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0x6c0627e1, __VMLINUX_SYMBOL_STR(nla_put_nohdr) },
	{ 0x6b2dc060, __VMLINUX_SYMBOL_STR(dump_stack) },
	{ 0x281be93d, __VMLINUX_SYMBOL_STR(passthru_features_check) },
	{ 0xf6f83b38, __VMLINUX_SYMBOL_STR(alloc_netdev_mqs) },
	{ 0x50fad434, __VMLINUX_SYMBOL_STR(round_jiffies_up) },
	{ 0x20f6b491, __VMLINUX_SYMBOL_STR(brioctl_set) },
	{ 0xbdafa0b9, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0xd8c5b317, __VMLINUX_SYMBOL_STR(netdev_err) },
	{ 0x32b3569f, __VMLINUX_SYMBOL_STR(ether_setup) },
	{ 0x5bdf1dce, __VMLINUX_SYMBOL_STR(__dev_get_by_name) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x341dbfa3, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0xf68ea58b, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x7e927f92, __VMLINUX_SYMBOL_STR(call_rcu_bh) },
	{ 0xb73d142a, __VMLINUX_SYMBOL_STR(unregister_netdevice_queue) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0x44da5d0f, __VMLINUX_SYMBOL_STR(__csum_ipv6_magic) },
	{ 0xe3a53433, __VMLINUX_SYMBOL_STR(dev_set_promiscuity) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xf48672df, __VMLINUX_SYMBOL_STR(dev_get_iflink) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x95977373, __VMLINUX_SYMBOL_STR(sysfs_create_bin_file) },
	{ 0x5dd37320, __VMLINUX_SYMBOL_STR(rtnl_link_register) },
	{ 0x97b3e71e, __VMLINUX_SYMBOL_STR(dev_uc_del) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x7d0db45c, __VMLINUX_SYMBOL_STR(jiffies_to_clock_t) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xe113bbbc, __VMLINUX_SYMBOL_STR(csum_partial) },
	{ 0x479986b2, __VMLINUX_SYMBOL_STR(consume_skb) },
	{ 0x67998e2b, __VMLINUX_SYMBOL_STR(netdev_update_features) },
	{ 0x85670f1d, __VMLINUX_SYMBOL_STR(rtnl_is_locked) },
	{ 0x7f02188f, __VMLINUX_SYMBOL_STR(__msecs_to_jiffies) },
	{ 0xef1393ba, __VMLINUX_SYMBOL_STR(sysfs_create_file_ns) },
	{ 0x10dd6b51, __VMLINUX_SYMBOL_STR(dev_queue_xmit) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x8cfff366, __VMLINUX_SYMBOL_STR(skb_put) },
	{ 0x751b5736, __VMLINUX_SYMBOL_STR(ipv6_mc_check_mld) },
	{ 0x27230ec7, __VMLINUX_SYMBOL_STR(__nlmsg_put) },
	{ 0x2560f12a, __VMLINUX_SYMBOL_STR(skb_copy_bits) },
	{ 0x6e720ff2, __VMLINUX_SYMBOL_STR(rtnl_unlock) },
	{ 0xc58a8cd, __VMLINUX_SYMBOL_STR(netdev_increment_features) },
	{ 0x14897a87, __VMLINUX_SYMBOL_STR(dev_set_mtu) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=stp,llc";


MODULE_INFO(srcversion, "7E868B4151A05413A9E8F30");
